### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by lynecro** [rspivak/lsbaws#4]
After running the pyramid server, I can get the response shown in the browser, but after a few seconds, below error was showing on the console and the server was down:
Traceback (most recent call last):
  File "webserver2.py", line 142, in <module>
    httpd.serve_forever()
  File "webserver2.py", line 41, in serve_forever
    self.handle_one_request()
  File "webserver2.py", line 51, in handle_one_request
    self.parse_request(request_data)
  File "webserver2.py", line 64, in parse_request
    request_line = text.splitlines()[0]
IndexError: list index out of range

**Comment by maxerogers** [comment]
Can confirm I had the same issue.
<img width="619" alt="screen shot 2015-12-22 at 3 46 56 pm" src="https://cloud.githubusercontent.com/assets/4670441/11965560/44e70b52-a8c3-11e5-8394-dbe3e376becf.png">

**Comment by zhwindy** [comment]
this error because your request text is None

**Comment by tanglongji** [comment]
我也遇到了，但是不知道怎么回事又没问题了
